### ISSUE TITLE
No issue ... just an invite :-)

### ISSUE THREAD

**Issue by Apollon77** [sammachin/node-red-matter-bridge#1]
Hey, 

just got aware of your useage of matter.js ...  Be invited (and als users) to join the Matter Integrators Discord (https://discord.gg/Zb7xNCQSjf) . Here you get teh most  infos on matter.js and we can also discuss your requiremens or wishes.

Ingo

**Comment by sammachin** [comment]
Thanks, I did join the other evening although I don't always have discord open, too many chat apps and I've still got legacy IRC channels :)
