### ISSUE TITLE
[Feature] Increment/Decrement Level control inputs

### ISSUE THREAD

**Issue by sammachin** [sammachin/node-red-matter-bridge#14]
When using a light with level control (dimmable, colour temp, full color) It would be really helpful to be able to send an input with a increment/decrement command that would adjust the level based on the existing level.

The size of a 'step' should be configurable in the node

**Comment by Apollon77** [comment]
Ideally not calucate yourself but use the "step" commands fro matter

**Comment by sammachin** [comment]
> Ideally not calucate yourself but use the "step" commands fro matter

but these inputs are coming from outside of the matter device, I thought it wasn't possible to invoke commands locally on the device you just have to set the attributes?

**Comment by Apollon77** [comment]
Ahh right you mean this case ... then yes ... just increase/decrese by step

**Comment by sammachin** [comment]
Fixed in https://github.com/sammachin/node-red-matter-bridge/commit/797cfccb0bd3d3fe9639b512ec080712108c81bf
