### ISSUE TITLE
FR - Doorbell device

### ISSUE THREAD

**Issue by Paul-Reed** [sammachin/node-red-matter-bridge#15]
Would it be possible to [add the doorbell device](https://developers.home.google.com/cloud-to-cloud/guides/doorbell) please?
...if of course it's available for Matter yet.
I'm currently using google's action console, but changing my flows over to matter.

TIA

**Comment by Apollon77** [comment]
If any CSA member or the industry wants to have this device type then it will be added. My personal assumption is that there might be chances whenever camera support is added because Doorbells are often connected to this.

**Comment by sammachin** [comment]
As I mentioned on discourse, there's no doorbell yet, but there is a Generic Switch which has a push button mode. 

This can then be configured in your Ecosystem to trigger an action like flashing lights or playing an announcement on your smart speakers, However at the moment I don't believe the Generic Switch device type is supported by Google Home, 
But it does work on Apple & Amazon.

FYI You can see a list of all the devices supported in the Matter spec here https://handbook.buildwithmatter.com/howitworks/devicetypes/

However that doesn't mean that all devices work on all controllers, its up to the individual ecosystems what they want to support.

With this project I've created all the device types that are supported by at least 2/3 of the major ecosystems Apple, Google, Amazon.
