### ISSUE TITLE
Connect to Tuya

### ISSUE THREAD

**Issue by petrknop01** [sammachin/node-red-matter-bridge#24]
Hey, Sam, 
I'd like to thank you for a great job. I have a question about connecting to Tuya. The bridge connects like a light bulb and no other devices are offered, do you happen to know what to do? Under google home everything works fine.

Thank you

**Comment by Apollon77** [comment]
In general also Tuya support support bridges in general for the supported device types (which are not that many tbh) ... Maybe please show a commissioning debug log

**Comment by sammachin** [comment]
@petrknop01 what other types of devices are you trying to add? Tuya only supports a very limited subset of Matter device types

**Comment by sammachin** [comment]
they should all work, what Tuya controller are you using, I've not tested with one here but I'll see if i can get hold of one in the UK

**Comment by sammachin** [comment]
I've done some testing now with the Tuya app on my iPhone and it looks like Tuya do not support bridges, hence the first device shows up as a basic lightbulb but is non-functional.

Until they implement bridge support in their controller these nodes won't work with Tuya.
