### ISSUE TITLE
turn on the lamp but I can't turn it off

### ISSUE THREAD

**Issue by Phillipp83** [sammachin/node-red-matter-bridge#29]
Hello and thanks for the great help. Unfortunately, 
I have a small problem. I can turn on the lamp with Alexa (Echo gen5), but I can't turn it off. Maybe you can give me a tip on what I need to do to make it work. 
Best regards, Philipp
![Screenshot 2024-12-21 134250](https://github.com/user-attachments/assets/3e269358-c854-49f5-907a-153e72b8a990)

**Comment by sammachin** [comment]
Hi,

what are the other nodes you are using for the lamp, likely you will need to do some mapping between the output of my nodes and what you lamp expects

**Comment by Phillipp83** [comment]
Thank you for the feedback.

I'm working with nodes on ioBroker and only need a true and false. However, when I switch, I get the value {"state":true} and {"state":false}. I tried to implement a translator, but then no values are received at all. I hope you understand what I've written since I wrote it in German and translated it via AI. 😉
![Screenshot 2024-12-28 165246](https://github.com/user-attachments/assets/55a5d601-4d3d-4470-b28c-77267194e201)

**Comment by sammachin** [comment]
So your io broker nodes expect a msg.payload of true/false? 

You should be able to just use a change node to move msg.payload.state to msg.payload in that case.

**Comment by Phillipp83** [comment]
Hello, 
and thank you for the great help. Everything works, including switching on and off with feedback on the switching state.
![Screenshot 2024-12-29 142055](https://github.com/user-attachments/assets/f0045724-18c1-4af4-b697-eeed2002c4b4)

**Comment by sammachin** [comment]
Glad its working, if you wanted to simplify your flows you could probabbly replace that group of switch & 2 function nodes with a change node like I showed but doing the reverse.

**Comment by Apollon77** [comment]
@Phillipp83 if you like contact me and join the testing for the ioBroker Matter adapter? :-)

**Comment by Phillipp83** [comment]
@sammachin 



> Glad its working, if you wanted to simplify your flows you could probabbly replace that group of switch & 2 function nodes with a change node like I showed but doing the reverse.

I tested your suggestion, unfortunately, it didn't work. Alexa switched, but in reality, the lamp didn't turn on or off. 

Perhaps a suggestion for improvement to the node: it would be useful to set the language for the inputs and outputs in the node. 

Thanks again, and have a great start to the new year.
