### ISSUE TITLE
Error Installing Node

### ISSUE THREAD

**Issue by Beormund** [sammachin/node-red-matter-bridge#3]
Node Red Version: 3.1.0

Immediately after installing the node I get the following error in the 'Manage Palette' UI:
<img width="557" alt="Screenshot 2023-10-22 at 10 30 37" src="https://github.com/sammachin/node-red-matter-bridge/assets/75735592/8ee05eaa-6a5a-4f78-8879-66d094137924">

**Comment by Apollon77** [comment]
Were there any error son npm install=? Which nodejs version do you use?

**Comment by Beormund** [comment]
> Were there any error son npm install=? Which nodejs version do you use?

I used 'Manage Palette' UI to install the node. 

From the logs: +

```
23 Oct 22:11:11 - [info] Node-RED version: v3.1.0
23 Oct 22:11:11 - [info] Node.js  version: v16.20.2
23 Oct 22:11:11 - [info] Linux 5.10.60-v7l+ arm LE
```
