### ISSUE TITLE
Node "color temp light" problem

### ISSUE THREAD

**Issue by umibozu83** [sammachin/node-red-matter-bridge#32]
I have a problem with the "color temp light" node when I use it, Node-Red crashes completely and does not restart. I attach the log of my Node-Red
[a0d7b954_nodered_2024-12-27T10-55-36.196Z.log](https://github.com/user-attachments/files/18259864/a0d7b954_nodered_2024-12-27T10-55-36.196Z.log)

**Comment by sammachin** [comment]
This is fixed in the latest release 0.11.4
