### ISSUE TITLE
on off light node : output message keep information from last input message

### ISSUE THREAD

**Issue by Lazare** [sammachin/node-red-matter-bridge#6]
I've set up an "on off light node" with "Passthrough Input msg to Output" set to true.
As output, when I toggle the light, I get the last message with only the payload modified.

For example, if my last input message was {"test": "something", "payload":{"state": true}} I get {"test": "something", "payload":{"state": false}} instead of {"payload":{"state": false}}. It seems to reset after an output is sent.

if "Passthrough Input msg to Output" set to false and there is a pending message in the input I don't get a message in the output

**Comment by Lazare** [comment]
Part of the problem seems to come from here :

```
        this.on('state', function(data){
            if ((node.pending && node.passthrough)) { // why do you keep last input message ?
                var msg = node.pendingmsg
                msg.payload.state=data
                node.send(msg);
            } else if (!node.pending){. // <-- this should just be else : if !node.passthrough we still want to get a message on state change.
                var msg = {payload : {}};
                msg.payload.state=data
                node.send(msg);
            }
            node.pending = false
        })
```

**Comment by Lazare** [comment]
My understanding of the problem:
the passthrough feature assume that when a message come into the input, the "input" and "state" events will be fired. But if the message payload contains the same state as the current state, the "state" event is not fired.

**Comment by sammachin** [comment]
I'm not quite sure if there's a problem here, it seems like its working as designed, however the concept is a little bit tricky to get your head around and I need to explain in the docs somewhere.

The Matter Bridge within node-red bascailly creates a bunch of virtual devices (like on/off light) each one represented by a Node.
That device maintains an internal state (on or off)
Your Matter controllers (apple home, Google Home etc) can then read that state and show it in the app. 
They can also send commands to change the state, turnOn, turnOff, toggle.
When the state changes (from a matter controller) the node will output a message.
You can also change the state externally to matter and to do this you would send an input message to the node.

This package is designed to allow you to link non matter devices to a Matter controller, so as such the state of the matter virtual device and the real device need to be in sync, therefore if your device can output its state you can feed that back into the Matter node to sync up the Matter state.
However if all messages just passed from input to output you would risk creating loops, hence the config option for passthrough.

So if the input to the Matter Node is coming from the output of a device and the output of the matter node goes to the device you may want to disable passthrough.

If you are using it where you have some other sort of manual control like a dashboard or just inject buttons going to the matter node then you would want passthorugh enabled to first update the matter state then send the actual state to the real device.

Does this make sense?

**Comment by Lazare** [comment]
The new change seems to handle the problem (not tested yet, just read the diffs)

Previously a new message could come into the input with the same state as the current state and then this message was kept pending (no 'state' event fired). Then later when toggling the state from apple home the message was not sent from the node as a message was already pending and the passthrough was off. 
So If the light was on and the node had previously received a message with state:on as it was already in state:on, then I had to toggle it 3 times 
first off (no message sent from the node because of the pending message) then on (a message sent but not usefull as the light was already on) then off (a message sent with state: off) and then my light would switch off.

**Comment by sammachin** [comment]
There shouldn’t be any changes around pass through between beta1 & beta2.

The topic state thing I added is for debugging the matter state.

I can see the scenario you mention now about an old Pending message coming though, need to think about how to expire those

**Comment by sammachin** [comment]
@Lazare I've made some improvements to the on/off light, socket and dimmable light in 0.11.0 around the passthrough so it should be more consistent, if you can let me know if this works for you I'll roll it out to the other nodes in the next version

**Comment by sammachin** [comment]
going to close this as I think I've got it right now in 0.11.2,

in Summary

Whenever a Matter Nodes state is changed from outside of Node-RED, eg using the Apple/Google/Amazon app then the node will output a new status value as a brand new message.

Whenever the node receives an input from another node then the node will only output the status if passthrough is set to true, this is consistent regardless of whether the device actual state changes.
