### ISSUE TITLE
FR: Support Battery and other well known properties?

### ISSUE THREAD

**Issue by Steve-Mcl** [sammachin/node-red-matter-bridge#9]
Hi Sam. It is feasible the nodes could support Battery level and other well known properties?

for example, matter devices generated by `Matterbridge` includes Battery Level  and Humidity

![image](https://github.com/user-attachments/assets/f7fd83cd-e8bf-403c-8241-2f58072cd2b3)

**Comment by sammachin** [comment]
Battery is certainly something I could add to pretty much all the devices, certainly to sensors and I guess it makes sense for thermostats too, I wasn't sure what the support for it was like across different platforms.

Humidity is a bit different, its not a standard attribute of the thermostat cluster in the spec, (unlike localTemperature) so what I think Matterbridge is doing is creating a composed device where you add multiple device clusters to a single endpoint. However it doesnt always show up properly in the controller.
You could add a separate humidty sensor node and device with the current pacakge, I'll have a think about humidity with thermostats....

Trying to figure out a way to do fully composable matter devices in node-red but I'm kinda stuck on ways to model it, as you'd need to create a node made up of multiple other nodes, maybe something with subflows or multiple config nodes, right now thats on the "hard problems" pile

**Comment by Steve-Mcl** [comment]
Sorry Sam. I wasn't clear - that was not a thermostat with humidity but rather one of those cheap battery powered temperature sensors which happens to have a humidity sensor too.

**Comment by sammachin** [comment]
Ah right I follow, yes thats got to be a composed devcice then made of up temp sensor & humidity sensor,

I've got them already in the package as separate nodes, depending on the UI of the controller if you put them in the same room they'll often show up together

**Comment by sammachin** [comment]
havn't forgotton about this but decided to leave it till 0.12 as there's so much in 0.11 in terms of code changes I didn't want to have a new feature to debug.

Basically I can add the power-source cluster to any device so that it will be able to report battery level (based on input)

**Comment by Steve-Mcl** [comment]
Thanks Sam.

**Comment by sammachin** [comment]
There's a 'preview' of this functionality in 0.11.3, see the changelog for details.
note I might change some of the inputs in a later version as we start to work out more around what controllers actually support out of the spec here.
early Christmas present for @Steve-Mcl

**Comment by Steve-Mcl** [comment]
Thanks Sam. Will be playing with this over Christmas.
